bcdice/BCDice

- src/Gemfile
最近のRubyの開発には bundler と呼ばれるライブラリ管理アプリを使って、依存関係をプロジェクトにダウンロードして、グローバルのGemを汚さないようにしています。
このPRではLinux向けの設定を追加しました。Windowsでも通るとは思います。
使い方は `$ gem install bundler` を行い、その後 `BCDice/src` に移動して、 `$ bundle install --path vendor/bundle` です
> Gemfile の追加

- src/bcdiceCore.rb
だいぶ古いですが 6702d1361f86915f6c21a2b92e4b0bafab5bb304 で追加されたマスターコマンド（設定コマンド）が実行できない問題の修正です。
メッセージを空白部分で切ってしまっていたため、`Set 〜` が最初の `Set` の部分しか認識されず、以降の引数が消えてしまっていました。open系コマンドと同様にマスターコマンドの場合は空白で切らないように変更しました。
修正に伴い正規表現を共通化したため、サブコマンドでの分岐も多少簡潔になっています。
> マスターコマンドが実行できない問題を修正する

- .gitignore
どどんとふのSWFと同様にリポジトリからbcdice.exeを削除しました。これによりリポジトリの容量が大幅に小さくなり、`git pull` が速くなることが期待できます。
1. どどんとふと同様に、バージョンアップ時に
```bash
git tag v2.02.67 # バージョンによって変える
git push --tags
```
でバージョンに対応したタグをアップロードします。
2. 実行ファイルを作成してフォルダをzipで固めます。
3. https://github.com/torgtaitai/BCDice/releases からタグのページに行き、zipファイルをアップロードします。
以上の手順で、そのバージョンの実行ファイルが含まれた配布用のファイルを掲載することができます。
> 実行ファイルをリポジトリから削除する

- src/log.rb
configBcDice.rbでデバッグ出力を行うかを決める変数 `$isDebug` を設定できますが、log.rbが読み込まれた際に強制的に `false` に変えられてしまうため、これまでデバッグ出力ができない状態になっていました。log.rbから `$isDebug` の設定を消すことで、BCDice単体でデバッグ出力を見ることができるようにしました。
> log.rb: $isDebugを上書きしないようにする

- src/cgiDiceBot.rb
BCDice単体の場合、Ruby 1.9以降でcgiDiceBot.rbが起動できない問題を修正しました。原因は$LOAD_PATHへのルートディレクトリの追加忘れでした。どどんとふで使う場合、どどんとふ側で$LOAD_PATHを設定しているため大丈夫だったようです。
> CgiDiceBot: $LOAD_PATHの追加し忘れを修正する

- src/diceBot/DiceBotLoaderList.rb
- src/test/testDiceBotLoaders.rb
先日追加された「ダークソウルTRPG」がDiceBotLoaderListに追加されていなかったため、追加しました。これにより、setGameで大文字小文字の区別なしでダイスボットを読み込めるようになります。
> DiceBotLoaderList: DarkSoulsを追加する

- src/createExe.rb
- src/diceBot/DiceBotLoader.rb
diceBotディレクトリ内の*.rbファイルを探してすべてのダイスボットを収集する処理をDiceBotLoaderに移しました。
この処理はexeファイル生成やどどんとふのDiceBotInfosで見られ、共通化が期待できます。また、diceBotディレクトリにあるDiceBotLoaderで `require_relative` と同様の読み込みを行うようにし、カレントディレクトリに影響されずに確実に読み込めるようにしました（どどんとふ側でBCDiceをサブモジュールにしようとしてディレクトリが変わった際に、特に効果的でした）。
> ダイスボット収集処理をDiceBotLoaderに移す

- src/configBcDice.rb
Ruby 1.9以降ではconfigBcDice.rbにおいて `$ircCode` を数値で指定するとエラーとなります。これは文字列のエンコーディングの実装の変更により、IntegerからEncodingに型が変わったためのようです。Kconvモジュールの定数を指定すればRuby 1.8でも1.9以降でも動作するため、そちらを使用するように変更しました。
> 設定：$ircCodeを数値で指定しないようにする

- src/diceBot/DiceBotLoader.rb
- src/test/testDiceBotLoaders.rb
コミット 5e7a2293deec15720e90769b4279ace842efc860 より未登録のダイスボット読み込み時にdiceBotディレクトリ内のファイルを列挙するようになりましたが、ファイルの列挙は一般に重い処理であるため、それを行わないようにしました。
上記コミットでのDiceBotLoaderの未登録のダイスボット読み込みについての変更は、クラス名として有効でないゲームタイプが指定された場合に、.rbファイルが存在してかつ `BOT_NAMES_TO_IGNORE` に掲載されていないと意図しないファイルが読み込まれてしまうという問題を解消するためと解釈しましたが、合っていますでしょうか？ 念のため、そのような問題が発生しないことを確認するテストを追加して実装しました。
> 未登録のダイスボット読み込みでファイルを列挙しないようにする

- src/Rakefile
- src/TableFileData.rb
- src/bcdiceCore.rb
- src/cgiDiceBot.rb
- src/diceBot/Airgetlamh.rb
- src/diceBot/BarnaKronika.rb
- src/diceBot/BattleTech.rb
- src/diceBot/BeginningIdol.rb
- src/diceBot/BeginningIdol_Korean.rb
- src/diceBot/CodeLayerd.rb
- src/diceBot/DiceBot.rb
- src/diceBot/EarthDawn.rb
- src/diceBot/EarthDawn3.rb
- src/diceBot/EarthDawn4.rb
- src/diceBot/Elysion.rb
- src/diceBot/Garako.rb
- src/diceBot/GoldenSkyStories.rb
- src/diceBot/HarnMaster.rb
- src/diceBot/Kamigakari.rb
- src/diceBot/Kamigakari_Korean.rb
- src/diceBot/MeikyuKingdom.rb
- src/diceBot/Paranoia.rb
- src/diceBot/ShinMegamiTenseiKakuseihen.rb
- src/diceBot/Utakaze.rb
- src/diceBot/ZettaiReido.rb
- src/test/DiceBotTest.rb
コード中でStringの破壊的メソッドを使わないようにした
- OpalがStringの破壊的メソッドをサポートしていないため (bcdice-js向け)
- Ruby 3系ではStringはimmutableになり、破壊的メソッドは利用不可になるため
結果の文字列生成などに、`String#<<` のような破壊的メソッドが使われていた。
```ruby
result = ""
result << "#{getFoo} ＞ #{getBar}"
```
```ruby
gameType.gsub!(':', '_')
```
`String#+=` などの非破壊的メソッドを使うようにした。
```ruby
result = ""
result += "#{getFoo} ＞ #{getBar}"
```
```ruby
gameType = gameType.gsub(':', '_')
```
テスト実行時にstringがimmutableであることを強制するようにした。
```ruby
sh('RUBYOPT="--enable-frozen-string-literal" ruby test.rb')
```
> Stringの破壊的メソッドを使わない

- src/diceBot/DeadlineHeroes.rb
デッドラインヒーローズのチャットコマンドの説明のデスチャートの部分。
例のサニティー-3がDCS3ではなく、DCC3になっておりました。
> デッドラインヒーローズのチャットコマンド説明、誤記修正

- README.md
- src/bcdice.rb
- src/diceBot/BarnaKronika.rb
- src/diceBot/DiceBot.rb
- src/diceBot/ShinkuuGakuen.rb
- src/diceBot/Warhammer.rb
- src/diceBot/_InsaneScp.rb
メソッド名・変数名に存在する、以下のスペルミスを修正しました。
* prefixs -> prefixes
* marker -> maker
* wapon -> weapon
* lisence -> license
* atack -> attack
API が変わりかねないため、気付いた中でも以下のスペルミスは修正していません(他にもあるかもしれません)。
* recive, recieve -> receive
- recieveMessage など
- $isRollVoidDiceAtAnyRecive
* uppler -> upper
- upplerRollThreshold など
`ruby src/test.rb` コマンドは全てパスしています。
以上、ご確認頂きますよう、よろしくお願い致します。
> メソッド名・変数名のスペルの修正

- .travis.yml
travis-ciのデフォルトOSが変わったことでRuby 1.9, 1.8のテストができなくなったのを解決する
> Set ci dist

- src/diceBot/StratoShout.rb
ストラトシャウトの判定処理に誤りがあったので、その修正です。
ストラトシャウトで2D6以外での判定は「作戦【ロジック】を使用して直前の判定を振り直す際、スキル【論理の律動】を組み合わせることで振り直しでの判定の達成値を［1D6+6］で算出する」という場合のみです。
一方で、スペシャルやファンブルは2D6の出目が特定の値の場合にのみ起こるとされています。
ですので、【ロジック】+【論理の律動】をするとスペシャルの処理もファンブルの処理も行わないのが正しい処理になるはずです。
元々の実装だと、1D6+6+n>=dをすると、1D6が1, 2の際にはファンブルと判定されていました。
1D6+6+n>=dは、単に成功か失敗かというだけならデフォルトの処理でいいので、check_nD6のオーバーライドは行わないようにしました。
> Fix action resolution for Strato Shout

- src/diceBot/DoubleCross.rb
レビューで指摘されたとおり、bcdice-jsでのOpal変換が煩雑になるため、正規表現を展開して書くように変えました。
> DoubleCross: 正規表現の埋め込みをやめる

- src/Gemfile
> Use json 2.2.0 due to Ruby 1.9

- src/diceBot/SwordWorld.rb
- src/test/data/SwordWorld.txt
レーティング表でピンゾロが出た時には補正があっても**を結果とする。
運命変転でダイスの出目そのものを変更する場合には、変更後の値を参照する。
Ref. #106
> レーティング表でピンゾロ時に、補正があっても**に

- src/diceBot/YankeeYogSothoth.rb
- src/test/data/YankeeYogSothoth.txt
ヤンキー＆ヨグ＝ソトースのダイスボットにおいて、一覧に記載があるものの実装されておらず、コマンドが反応していなかった「二つ名決定表 (コマンド: `FTNT`)」が実行可能になるよう修正しました。
また、元々「二つ名表」と記載がありましたが、ルールブック内での正式名称は「二つ名決定表」でしたので名称を修正しています。
二つ名の決定は、ルールブック記載の通り
1. まず1d6を振り、4つある `二つ名表` の中からどの表を使用するか決定
2. d66を振り、`1.` で決めた表の中から二つ名を決定
の順に処理を行って結果を表示しています。
不備・改善点がありましたらご指摘お願います。
> ヤンキー＆ヨグ＝ソトース：二つ名決定表の実装とテストを追加

- src/diceBot/NinjaSlayer.rb
- src/test/data/NinjaSlayer.txt
NinjaSlayerのNJコマンドでシークレットロールできないのを修正しました。`changeText` で参照する正規表現において、シークレットロールを示す先頭の `S` を考慮していませんでした。
> NinjaSlayer: NJコマンドでシークレットロールできないのを修正する

- Gemfile
Ruby 1.9はjson 2.3以降だと動かない。しかしRuby 2.7でjson 2.2を使うと大量にwarningがでるため、Ruby 1.9以外では新しいのを使う。
> Ruby 1.9の時だけjson gemのバージョンを指定する

- src/diceBot/WorldOfDarkness.rb
- src/test/data/WorldOfDarkness.txt
原作者による2018-11-25版のtest caseを基に書き換えました。
> WorldOfDarkness: fix. add STA for 20th Ed.

- src/diceBot/ShadowRun4.rb
ヘルプ未記載およびテストに記載なしの`nS6`をシャドウラン第4版から削除
Ref. #127
> シャドウラン第4版から非サポートのコマンドを削除

- src/bcdiceCore.rb
- src/cgiDiceBot.rb
BCDice内部ではExtratablesを利用しなくなったため、 #43, #50 などでサポートから外したが、どどんとふで `BCDice#getTableDataResult` などを利用していたため、復活させる
> Extratablesを復活

- src/cgiDiceBot.rb
#134 でダイスロールの詳細を保持するようになったが、CgiDiceBotからもそれを見れるようにする。これはbcdice-jsなどの外部ツールがCgiDiceBot経由でダイスロールしているためである。
`BCDice#rand_results`と`BCDice#detailed_rand_results`へのエイリアスをそれぞれ作成した。
> CgiDiceBotも乱数詳細を返すように

- Rakefile
- src/dice/add_dice/node.rb
- src/test/add_dice_parser_test.rb
構文解析のデバッグを行いやすくするために、AddDiceの抽象構文木のノードにS式を返すメソッドを追加しました。また、このメソッドを使用して、構文解析結果の抽象構文木が正しいことを確認するテストを追加しました。
> AddDice::Node: ノードのS式を返すメソッドを追加する

- src/TableFileData.rb
- src/diceBot/DiceBotLoader.rb
Object#untaint is deprecated. It will be removed Ruby 3.2.
> Remove Object#untaint

- src/dice/add_dice/node.rb
- src/dice/add_dice/parser.rb
除算ノードのクラスを新しく作り、BinaryOpを単純化しました。
除算の処理だけが特別なので、汎用的なBinaryOpにそれを書くのではなく、端数処理方法別に除算ノードのクラスを3つ作り、それらに処理を分担させました。
クラスの継承関係：
BinaryOp（二項演算子）
|
+-- DivideBase（除算の基底クラス）
|
|-- DivideWithRoundingUp  （除算 -> 切り上げ）
|-- DivideWithRoundingOff （除算 -> 四捨五入）
+-- DivideWithRoundingDown（除算 -> 切り捨て）
> AddDice::Node: 二項演算子をリファクタリングする

- src/diceBot/ArsMagica.rb
- src/test/data/ArsMagica.txt
ArsMagicaのテストで成功失敗判定のテストケースがなかったため、 `DiceBot#check_result` のリファクタリング(#145)で修正漏れしていた。 
問題を修正し、該当するテストケースを追加。
また、重複するテストケースを排除。
> ArsMagicaで成功失敗判定ができない問題を修正

- src/bcdiceCore.rb
- src/diceBot/DiceBot.rb
Fixes #178
※IRCボット機能は後にまとめて削除する予定ですが、このPR内のコミットはDiceBotにも影響するため、変更範囲が小さいうちに投稿します。
IRCボット用のマスターコマンドから、ソード・ワールドのレーティング表設定コマンドを削除します。
引数の数の不一致により、以前からこのコマンドを実行するとArgumentErrorが発生するようになっていました。
また、同時に不要になった `DiceBot#setRatingTable` も削除します。
そのため、この名前のメソッドはソード・ワールドのダイスボットに固有のメソッドに変わります。
> マスターコマンド：レーティング表設定コマンドを削除する

- Rakefile
- src/diceBot/SamsaraBallad.rb
- src/test/data/SamsaraBallad.txt
- src/test/test_command_parser.rb
- src/utils/command_parser.rb
コマンドからクリティカル、ファンブル、修正値、比較演算子、目標値をパースする汎用パーサーを追加する。使い方は下記の通り。
```ruby
parser = CommandParser.new("LL", "LR") # 使うコマンドを列挙
cmd = parser.parse("LL@1#2+4<=5")
cmd.command #=> "LL"
cmd.critical #=> 1
cmd.fumble #=> 2
cmd.modify_number #=> 4
cmd.cmp_op #=> :<=
cmd.target_number #=> 5
```
良い名前が思い浮かばなかったので、`CommandParser` `CommandParser#command` にしたが、代替案があれば変更したい。
> 汎用コマンドパーサー

- src/CardTrader.rb
- src/bcdiceCore.rb
Refs #211 
Refs bcdice/bcdice-irc#31
ヘルプコマンド（`help`、`c-help`）をBCDice IRCに移すため、削除しました。
また、`help` では、現在指定されているダイスボットを参照する必要があったため、BCDiceクラスに `attr_reader :diceBot` を追加しました。従来は BCDiceMaker#diceBot がありましたが、どどんとふも含めてどこからも参照されていなかったため、こちらは削除しました。
> ヘルプコマンドを削除する

- src/CardTrader.rb
- src/bcdiceCore.rb
Fixes #211 
Refs bcdice/bcdice-irc#32
マスターコマンドをBCDice IRCに移すため、削除しました。マスターコマンドに必要な `BCDiceMaker#master`等のニックネーム記録処理もBCDice IRCにすべて移せたため、削除しました。
> マスターコマンドを削除する

- src/bcdiceCore.rb
- src/test/data/None.txt
加算ダイスの先頭がダイスロールリテラルでない時に加算ダイスと認識しない問題があった
> 一部の加算ダイスでシークレットにならない問題を修正

- src/cgiDiceBot.rb
- src/configBcDice.rb
- src/diceBot/BattleTech.rb
- src/diceBot/DoubleCross.rb
- src/diceBot/RecordOfSteam.rb
- src/diceBot/SwordWorld.rb
Fixes #225 
IRCボット機能の削除により不要になった、メッセージの最大文字数制限の設定項目（`$SEND_STR_MAX`）を削除します。また、この設定を参照する、各ダイスボットのメッセージ短縮処理も削除します。
> メッセージの最大文字数制限を撤廃する

- Rakefile
- src/test/test_data_encoding.rb
ただのテキストファイルの文字コードと改行コードをチェックする仕組みがなかったので、PRで寄稿されたテストケースがSJISでCRLFなテキストだったとしてもCIをPassしてしまう。
テストデータの文字コードと改行コードをチェックするテストを作成してこの問題を回避する。
> テストデータの文字コードと改行コードをチェックするテストを追加

- src/diceBot/TorgEternity.rb
- src/test/data/TorgEternity.txt
`TG12+5`が`TG5`と等価になってしまうバグを修正
| Input | 修正前 | 修正後 |
| :----- | :----- | :----- |
| TG12+5 | 1R20+5 | 1R20+(12+5) |
| TG5 | 1R20+5 | 1R20+5 |
| TG+5 | 1R20+5 | 1R20+5 |
| TG+1+2+3 | 1R20+3 | 1R20+(1+2+3) |
加えて、不適切な `Regexp.last_match` の利用を修正
> TORG EternityのTGコマンドのバグ修正

- src/diceBot/BeastBindTrinity.rb
- src/test/data/BeastBindTrinity.txt
- 表類のクラスを使う
- 判定コマンドの処理をクラスに切り出す
[Regexperによる可視化](https://regexper.com/#%2F%5E%28%5Cd%2B%29%28%3F%3AR6%7CBB6%3F%29%28%28%3F%3A%5B%5C%2B%5C-%5D%5Cd%2B%29%2B%29%3F%28%3F%3A%25%28%5C-%3F%5Cd%2B%29%29%3F%28%3F%3A%40%28%5B%5C%2B%5C-%5Cd%5D%2B%29%29%3F%28%3F%3A%23%28A%29%3F%28%5B%5C%2B%5C-%5Cd%5D%2B%29%29%3F%28%3F%3A%5C%24%28%5B1-6%5D%2B%29%29%3F%28%3F%3A%26%28%5B1-6%5D%29%29%3F%28%3F%3A%28%5B%3E%3D%5D%2B%29%28%5Cd%2B%29%29%3F%24%2F)
- `%<number>`: humanityの指定。この値によってクリティカル値のベースが変更される
- `@<number>`: 
- 符号ありの場合: クリティカル値のベース + `<number>` をクリティカル値とする
- 符号なしの場合: `<number>` をクリティカル値とする
- `#A<number>`:
- ファンブル値を `<number> `にする
- 符号の有無による挙動はファンブルと同様
- `A` がつく場合:  ファンブルした場に達成値を維持する
- `A` がない場合: ファンブルした時に達成値を0にする
- `$<number 1><number 2>...`: 事前にダイス目を指定する
- `&<number>`: `<number>` 未満のダイス目を `<number>` …
> BeastBindTrinityのリファクタリング

- lib/bcdice/game_system/GURPS.rb
https://github.com/bcdice/BCDice/commit/a105181596be99799c254a122225c8400b78290a#diff-edecff1d1db5953fb49c6a7247df7aabecbf6edfb9faff9799cdd1ca487d3fc3R5 で、GURPSのクラス名が `GURLS` に変わっていたので、修正しました。
> GURPSのクラス名を修正する

- lib/bcdice/base.rb
- lib/bcdice/preprocessor.rb
- test/data/BarnaKronika.toml
- test/data/DarkBlaze.toml
- test/data/EarthDawn.toml
- test/data/EmbryoMachine.toml
- test/data/GehennaAn.toml
- test/data/Nechronica.toml
- test/data/Nechronica_Korean.toml
- test/data/None.toml
- test/data/Torg.toml
コマンドに `[1...6]` や `[1D6]` と書くと事前処理でダイスロールされていたが、これを廃止する。
マニュアルにも記載されておらず、不要な機能となっている。
> 事前処理によるダイスロールを廃止

- .github/workflows/test.yml
脆弱性があったらしく `set-env` が消えたので、新しい手法に切り替える
> `set-env` command is disabled

- lib/bcdice/common_command/reroll_dice/node.rb
RerollDice::Nodeを次のように変えました。
* 短いメソッド、および一時的な値を保持するのみのインスタンス変数を、ローカル変数に変える。
* 1行のみの短いメソッドを、`#eval` 内のローカル変数に変えました。これらは `#eval` から順番に1回ずつ呼び出されるだけでした。
* この変更により、一時的な値を保持するのみのインスタンス変数も不要になりました。 
* `private` な `attr_reader` を単純にインスタンス変数で参照する。
* 振り足し条件をクラスに切り出す。
* 様々な場所で、振り足し判定用比較演算子と閾値のペアが必要になっていました。そのため、このペアをクラスにまとめました。
* `#expr`: `reroll_cmp_op_text`: 文字列であることを明示する。
* 変更前は、後置 `if` で条件を満たさない場合は `nil` が代入されることに注意する必要がありました。
> RerollDice::Nodeをリファクタリングする

- lib/bcdice/common_command/choice.rb
- test/data/None.toml
- test/data/choice.toml
```
choice[A,B,C,D]
choice(A,B,C,D)
choice A B C D
choice(新クトゥルフ神話TRPG, ソード・ワールド2.5, Dungeons & Dragons)
```
`"choice"`の次の文字によって区切り文字が変化する
- `"["` -> `","` で区切る
- `"("` -> `","` で区切る
- 空白文字 -> `/\s+/` にマッチする文字列で区切る
各項目の前後に空白文字があった場合は除去される
- `choice[A, B,  C , D   ]` は `choice[A,B,C,D]` と等価
項目が空文字列である場合、その項目は無視する
- `choice[A,,C]` は `choice[A,C]` と等価
フォーマットを選ぶことで、項目の文字列に`()`や`,`を含めることができる
- `choice A,B X,Y` -> `"A,B"` と `"X,Y"` から選ぶ
- `choice(A[], B[], C[])` -> `"A[]"`, `"B[]"`, `"C[]"` から選ぶ
- `choice[A(), B(), C()]` -> `"A()"`, `"B()"`, `"C()"` から選ぶ
> Choiceで半角スペースを扱えるようにする

- lib/bcdice/game_system/CthulhuTech.rb
- lib/bcdice/game_system/DoubleCross.rb
- lib/bcdice/game_system/NinjaSlayer.rb
- lib/bcdice/game_system/SwordWorld.rb
- lib/bcdice/game_system/SwordWorld2_0.rb
- lib/bcdice/game_system/SwordWorld2_5.rb
Ruby 2.4以降で使える意図の明確なメソッドを活用して、各ゲームシステムに含まれていたTODOの一部を除去しました。また、条件を満たす要素の個数カウントに `array.select.length` という冗長な記述があったので、`Array#count` を使うように変えました。
> より意図の明確なメソッド（Ruby 2.4以降で使用可能、Array#count）を使う

- lib/bcdice/preprocessor.rb
- test/data/DoubleCross.toml
- test/test_preprocessor.rb
- `(8-1)+(5+5)` が `17` になってしまう問題を修正 (Fix #318)
- 不正な式だった時には `0` にぜすにそのままにしておく
> [Preprocessor] 四則演算の誤った展開を直す

- lib/bcdice/common_command/barabara_dice/node.rb
- lib/bcdice/common_command/barabara_dice/result.rb
- lib/bcdice/game_system/NinjaSlayer.rb
- lib/bcdice/result.rb
バラバラロール（`xBn`）の結果を表すクラスを作り、通常の結果に加えて出目と成功数を記録するようにしました。
目的は、BarabaraDiceの結果オブジェクトから必要な項目を直接取得できるようにすることです。これまでは結果が文字列でしか得られなかったため、ニンジャスレイヤーTRPG等では結果の文字列から必要な部分を抽出して判断していました。この方法はバラバラロールの出力書式に依存するため、書式の変更に弱いです（i18nを行う場合は、さらに言語数分だけ修正作業が多くなります）。結果オブジェクトから必要な項目を直接取得できれば、書式を考慮する必要がなくなります。
実装では `BCDice::Result` を継承するクラス `BCDice::CommonCommand::BarabaraDice::Result` を作りました。追加したのは成功数（`success_num`）のみです。出目の記録には、`BCDice::Base#eval` の最後で設定される `#rands` と `#detailed_rands` を使用しましたが、これでも大丈夫でしょうか？
作った仕組みを使って、ひとまずニンジャスレイヤーTRPGのTODO整理を行いました。他にはシャドウラン5th Editionに適用できそうです（ただ、シャドウラン5th EditionではニンジャスレイヤーTRPGよりもアドホックな処理が多かったため、今回は適用を見送りました）。
> バラバラロール（xBn）の結果に出目と成功数を加える

- lib/bcdice/common_command/add_dice/node.rb
- lib/bcdice/common_command/add_dice/parser.rb
- lib/bcdice/common_command/add_dice/parser.y
- test/data/AddDice.toml
- test/test_add_dice.rb
AddDiceで除算の端数処理は切り捨て固定だったが、ゲームシステムの設定によって挙動が変わるようにする。
また、切り捨てを明示する `3/2F` の記法を追加する。
なお、BarabaraDiceなど他のCommonCommandはすでにゲームシステムの設定によって端数処理の挙動が変わるようになっている。
> [AddDice] 除算の端数処理をゲームシステム依存にする

- lib/bcdice/base.rb
- lib/bcdice/common_command/add_dice/node.rb
- lib/bcdice/common_command/add_dice/parser.rb
- lib/bcdice/common_command/add_dice/parser.y
- lib/bcdice/preprocessor.rb
- test/test_add_dice.rb
- test/test_add_dice_parser.rb
- test/test_preprocessor.rb
`1D+4` と入力された場合、今までは6面ダイス扱いとし `1D6+4` と解釈するようになっていた。
しかし、ゲームシステムによっては`1D`で期待される暗黙の面数は異なる。そこで、`BCDice::Base`に設定項目`@sides_implicit_d`を追加し、ゲームシステムごとに`1D`の解釈を変えられるようにする。
- 設定`@sides_implicit_d`の追加
- AddDiceで`@sides_implicit_d`を参照する
- Preprocessorで`@sides_implicit_d`を参照する
> ダイスの面数が省略された場合の面数をゲームシステムごとに指定できるようにする

- lib/bcdice/game_system/Cthulhu7th.rb
- test/data/Cthulhu7th.toml
ボーナス・ペナルティダイス数は英語原文だと明言されているが、日本語訳に意味が抜け落ちている。
ボーナスダイスに影響を与える呪文が未翻訳の英語版に複数あることや、上限についてはKPの裁量によるところが大きいため上限を緩和する。
Close #342
> [Cthulhu7th] 技能判定のボーナスダイス数を100まで緩和する

- lib/bcdice/randomizer.rb
- test/test_randomizer.rb
繰り返しコマンドを実装したことで悪意のあるコマンドを注入しやすくなったため、
コマンドにおける乱数生成に上限を設ける。
上限に達した場合、例外を発生させる。
BCDiceではこの例外をキャッチせず、ハンドリングはライブラリ利用者に委ねる。
この例外をBCDiceでキャッチしてエラーメッセージに変換した方が良いかどうか
> コマンドあたりの乱数生成の上限回数を10000回にする

- lib/bcdice/game_system/DoubleCross.rb
- test/data/DoubleCross.toml
オンセツールの機能を使って負の数を埋め込みしようとするとこのような現象が起こる。
`Command::Parser` を使ってパースする。
Ref. https://twitter.com/A_zondag/status/1305838316584009730
> システムはダブルクロスです
ステータスにw,xを設定しています
>
>使用している式です
({精神}+{DB}+{x})DX(8-{z})+{白兵}+{w}　命中判定
wに-の値が入ると判定がうまくいきません
> [DoubleCross] DXの修正値で `1+-4` となったときに動くように

- i18n/DetatokoSaga/ja_jp.yml
- i18n/DetatokoSaga/ko_kr.yml
- lib/bcdice/game_system/DetatokoSaga.rb
- lib/bcdice/game_system/DetatokoSaga_Korean.rb
- test/data/DetatokoSaga.toml
- test/data/DetatokoSaga_Korean.toml
でたとこサーガのダイスボットについての2つの修正です。
修正1) ダイスボットの誤植修正
　ダイスボットでは「スキルレベル」と出力されているが、ルールブックの記述では「スキルランク」となっている。
ルールブックの記述に合わせた誤植の修正を行ったものです。
修正2) 通常判定 xDS の機能拡張
　通常判定コマンド xDS では、現在の挙動では修正値を受け付けません。
ルールに記載されたスキル効果などで、修正値を加えることがあります。
現状の挙動のままでは、ユーザは 2DS3 と入力し、出力を受けてから
手作業で修正値の分を計算する形になります。
　利便性を向上させるため、 xDS コマンドも +- の修正値に対応するよう
拡張したものが修正2になります。
付記
　修正2では、修正内容が多言語化ファイルへも影響するため
韓国語版についても変更を加えています。
確認よろしくお願いします。
> でたとこサーガの誤植修正、通常判定の拡張。

- lib/bcdice/game_system/AlchemiaStruggle.rb
- test/data/AlchemiaStruggle.toml
アルケミア・ストラグルのセッションをしてみて、ほぼ必須レベルに欲しいコマンドがあったので、その追加です。
- ウルダイスの獲得 `xUL`  
戦闘時に各PCが最大18D6を振り、その出目を数える処理がある。人力だとつらいので専用コマンドを作成
- 共通コマンドのダイスソート  
システム専用コマンドを使わなかった場合でもxD6からy個を選択しやすいように
- 端数切り上げ
ルールブックp.6
> [AlchemiaStruggle] ウルダイス用コマンド追加

- test/test_game_system_commands.rb
Rakeタスク `test:dicebots` で、複数のゲームシステムを指定できるようにしました。例えば、SwordWorld・SwordWorld2\_0・SwordWorld2\_5のような、クラス継承によって動作が引き継がれる複数のゲームシステムのテストをまとめて実行できるようになり、動作確認の効率向上が期待できます。
`rake test:dicebots` で環境変数 `target` を用いる際、カンマ区切りでテストデータファイル名を並べます。
```
bundle exec rake test:dicebots target=SwordWorld,SwordWorld2_0,SwordWorld2_5
```
このように記述して実行すると、並べた順にテストケースが追加されて、テストが実行されます。
存在しないテストデータファイル名を指定すると、そのファイルが無視されて、残りのテストが実行されます。
```
$ bundle exec rake test:dicebots target=SwordWorld,SwordWorld2
Unknown target: test/data/SwordWorld2.toml
Loaded suite ...
Started
...
```
すべてのファイルが無視された（＝テストケースがない）場合はエラーとなり、終了コード1で終了します。
```
$ bundle exec rake test:dicebots target=SwordWorld2
Unknown target: test/data/SwordWorld2.toml
No target found!
rake aborted!
Command failed with status (1)
```
> テスト：複数のゲームシステムを指定可能にする

- lib/bcdice/game_system/Garako.rb
- test/data/Garako.toml
`GR`や`GR+5#2`のように、目標値が無くても振れるように
> ガラコの判定の目標値を省略可能に

- lib/bcdice/game_system/SwordWorld2_5.rb
- test/data/SwordWorld2_5.toml
SW2.5のモンストラスロアで追加されたドルイド技能（森羅魔法）において、
一部魔法で特異なダメージ算出方法が追加されました。
威力決定の際に威力表を参照せず、2d6の出目の範囲に応じて
- 出目が2-6の時は「A+魔力」点のダメージ
- 出目が7-9の時は「B+魔力」点のダメージ
- 出目が10-12の時は「C+魔力」点のダメージ
という形でダメージを算出しています。このA、B、Cの値は、使用する魔法によって異なっています。
「ダメージ算出」であるという性質上加減算などが必要になり、 単純なダイス表で表現するのも難しいため、専用のダイスコマンドを実装いたしました。
> SW2.5のモンストラスロアで追加された森羅魔法のダメージ算出ダイスに対応

- lib/bcdice/game_system/BeastBindTrinity.rb
- test/data/BeastBindTrinity.toml
> [BeastBindTrinity] 判定コマンドで大きい方から取る処理が抜けていた

- lib/bcdice/game_system/ShinobiGami.rb
- test/data/ShinobiGami.toml
Discordにこのバグが報告された
```
p.p.今日 17:40
お世話になっております。
1. ココフォリア
2. シノビガミ
3. SG@5#7
4. SG (SG@5#7) ＞ 5[1,4] ＞ 5 ＞ スペシャル(【生命力】1点か変調一つを回復)
5. シノビガミのシステムではファンブル値とスペシャル値が競合した場合ファンブル値が適用されます。なので上記の入力の場合ダイスによる達成値が5の場合ファンブルと出力されるのが正しいです。
BCDice/lib/bcdice/game_system/ShinobiGami.rbを読んだかぎり112行目から115行目のif、elseifの処理順を逆にすれば修正できるかなと。
```
> [ShinobiGami] 行為判定ではクリティカルよりもファンブルが優先される

- lib/bcdice/game_system/Cthulhu.rb
- test/data/Cthulhu.toml
> [Cthulhu] 完全一致にする

- lib/bcdice/game_system/SwordWorld2_0.rb
- lib/bcdice/game_system/sword_world/transcendent_test.rb
超越判定について、パース処理をCommand::Parserを使った形に書き換え、超越判定の処理クラスをsword_worldディレクトリに移動しました。
> [SwordWorld2.0] 超越判定のリファクタリング

- lib/bcdice/game_system/Cthulhu7th_ChineseTraditional.rb
- lib/bcdice/game_system/Cthulhu7th_Korean.rb
- lib/bcdice/game_system/Cthulhu_ChineseTraditional.rb
- lib/bcdice/game_system/Cthulhu_Korean.rb
- lib/bcdice/game_system/MeikyuKingdomBasic.rb
- test/test_sort_key.rb
BCDice 3.1.0であやまったSORT_KEYを混入させてしまったので、仕様に適合するかチェックするかテストします。
> SORT_KEYをテストする

- lib/bcdice/common_command/add_dice.rb
- lib/bcdice/dice_table/sai_fic_skill_table.rb
- test/test_base.rb
- test/test_sai_fic_skill_table.rb
`BCDice::Base#register_prefix` にRegexpのインスタンスが渡されると、 `BCDice::Base#command_pattern` がJavaScript等で解釈できない応答になるため修正する。
`register_prefix` にRegexpが渡されると以下のようになってしまう。 `(?-mix:RTT[1-6]?)` の部分がJavaScriptでは解釈できない。
```ruby
/^S?([+\-\dD(]+|\d+B\d+|C|choice|D66|(repeat|rep|x)\d+|\d+R\d+|\d+U\d+|BCDiceVersion|(?-mix:RTT[1-6]?)|RCT)/i
```
> SaiFicSkillTableのcommand_patternがRuby依存にならないように

- lib/bcdice/common_command/add_dice.rb
- test/test_base.rb
- test/test_sai_fic_skill_table.rb
AddDiceの`PREFIX_PATTERN`を変更して、下記のようなコマンドが`command_pattern`にマッチしないようにする
- `D6`
- `+-`
https://discord.com/channels/597133335243784192/677433815756439562/828206792860368906
> AddDiceのPREFIX_PATTERNをより厳密に

- lib/bcdice/game_system.rb
- lib/bcdice/game_system/Ainecadette.rb
- test/data/Ainecadette.toml
[先輩後輩TRPG エネカデット](http://www.bouken.jp/pd/ac/)
```
■ 判定
- 先輩 (AI) 10面ダイスを2つ振って判定します。『有利』なら【3AI】、『不利』なら【1AI】を使います。
- 後輩 (CA) 6面ダイスを2つ振って判定します。『有利』なら【3CA】、『不利』なら【1CA】を使います。
```
> 先輩後輩TRPG エネカデットに対応

- lib/bcdice/game_system/ShinobiGami.rb
- test/data/ShinobiGami.toml
一部の技能で行為判定時に2D6でなく3D6や4D6から出目を2つ選んで達成値にする効果がある。 `SG`コマンドでその対応として`nD6KH2`相当の処理を実行できるようにする。
> [ShinobiGami] 行為判定コマンドでダイス数を指定できるようにする

- lib/bcdice/game_system/MonotoneMuseum.rb
- test/data/MonotoneMuseum.toml
- test/data/MonotoneMuseum_Korean.toml
#423 
MonotoneMuseum および MonotoneMuseum:Korean の対応
- 自動成功 -> `critical`
- 自動失敗 -> `fumble`
MonotoneMuseum:Korean のテストケースの内容が日本語版と差異があったため移植した
> [MonotoneMuseum] Resultに対応する

- lib/bcdice/game_system/StellarKnights.rb
- test/data/StellarKnights.toml
#423 
---
　成功／失敗の概念があるのは、【アタック判定】に防御力との比較が指定された場合のみであるはず。
　当該の【アタック判定】において、成功数が１以上ならば成功、成功数が０ならば失敗とみなす。
　基本ルールブック『銀剣のステラナイツ』の時点では「失敗」という表現はもちいられていないが（同書p150）、『銀剣のステラナイツ　星屑のリヴラガーデン』p119では同じ意味合いの処理に対して「失敗」という表現がされているため、この方針で妥当だと考える。
　成功数が 0 になるテストケースがもともとなかったので、それも追加してある。
> [StellarKnights] success/failure を明示

- lib/bcdice/game_system/SamsaraBallad.rb
- test/data/SamsaraBallad.toml
> [サンサーラ・バラッド] Result対応

- lib/bcdice/game_system/BeastBindTrinity.rb
- test/data/BeastBindTrinity.toml
#423 対応
クリティカル、ファンブル、成功失敗について、テキストに記載がある通りにResultに設定
> [BeastBindTrinity] Result対応

- lib/bcdice/game_system/ColossalHunter.rb
- test/data/ColossalHunter.toml
#423 コロッサルハンターに対応
※`nCH`に対応してそうなロジックだったが、最初期から`prefix`の指定ミス？で利用できない状態だった。
https://github.com/bcdice/BCDice/blob/ffa352a7c8efc109fa1461a57a4e4b71d79ee1f3/src/diceBot/ColossalHunter.rb
攻撃判定のダイスを増やす能力が存在するため、使用できるように。
> [ColossalHunter] Resultの使用

- lib/bcdice/game_system/SRS.rb
- test/data/Alshard.toml
- test/data/EtrianOdysseySRS.toml
- test/data/FullMetalPanic.toml
- test/data/MetallicGuardian.toml
- test/data/SRS.toml
#423 
SRS および SRS を継承しているシステムの Result 対応
- SRS: スタンダードRPGシステム
- Alshard: アルシャード
- EtrianOdysseySRS: 世界樹の迷宮SRS
- FullMetalPanic: フルメタル・パニック！RPG
- MetallicGuardian: メタリックガーディアンRPG
備考
いくつかのシステムで `failure` のテストケースが存在しなかったため修正しました
> SRS系列のResult対応

- lib/bcdice/game_system/AnimaAnimus.rb
- test/data/AnimaAnimus.toml
#423 のResult対応をしました。
Regexp.last_matchの削除とArithmeticEvaluator.evalからArithmetic.evalへの変更も行いました。
> [AnimaAnimus]Result対応

- lib/bcdice/game_system/Amadeus.rb
- test/data/Amadeus.toml
- test/data/Amadeus_Korean.toml
#423 Amadeus, Amadeus:Korean
アマデウスでの能力値判定では複数個のダイスを振り、そのうちの1つを選択して判定に用いる。
そのため、コマンドの結果にはそれぞれのダイスの成功/失敗/スペシャル/ファンブルが示されている
複数個のダイスを振った場合、success/failure/critical/fumbleは次の順に判定する
1. スペシャルがある → `success` かつ `critical`
2. 1つ以上成功している → `success`
3. 成功が無い、かつ、ファンブル → `failure` かつ `fumble`
4. 上記以外 → `failure`
success/critical と failure/fumble が同時に `true` にならないようにしている
> [アマデウス] リファクタリングおよびResultの使用

- lib/bcdice/command/parsed.rb
- lib/bcdice/command/parser.y
- test/test_command_parser.rb
`2NX13>=10` のようなコマンドをCommand::Parserで扱う際に `NX` の前後の数値を取得しやすいようにします。
- `Parsed#prefix_number`
- `Command::Parser#command`の直前にある数値
- `Parsed#suffix_number`
- `Command::Parser#command`の直後にある数値
- `Parser#has_prefix_number`
- prefix_numberがパースされることを**強制**する
- `Parser#has_suffix_number`
- suffix_numberがパースされることを**強制**する
- `Parser#enable_prefix_number`
- prefix_numberがパースされることを**許可**する
- `Parser#enable_suffix_number`
- suffix_numberがパースされることを**許可**する
` Command::Parser.new(/\d+D6/)` などとすると、`0D6`に対して `"0D6".to_i`が6になってしまうことがわかり、パーサー側で自動判別できた方が良いだろうという話になった。 `0d`はRubyで10進数の接頭辞として扱われる。
Ref: https://docs.ruby-lang.org/ja/latest/method/String/i/to_i.html
> Command::Parserでコマンドの前後の数値をパースできるようにする

- lib/bcdice/game_system/BattleTech.rb
- test/data/BattleTech.toml
Refs #423
`BT` コマンドの結果に成功/失敗を設定するようにしました。 #445 と合わせると、バトルテックの成功/失敗実装が完了します。
> BattleTech: BTコマンドの結果に成功/失敗を設定する

- lib/bcdice/game_system/ZettaiReido.rb
- test/data/ZettaiReido.toml
> [ZettaiReido] Result対応

- lib/bcdice/game_system/Satasupe.rb
- test/data/Satasupe.toml
Satasupeに対する #423 対応です。
このシステムのダイスにおいては、「目標成功度」はあくまでダイスの振り足しを止める成功度という指定で、必ずしもこれが判定の成否の閾値となる成功度とは限らず、現在は振り手にとっての成功失敗を判断する情報がないため、基本的に `success` , `failure` と断定できるもの以外は、どちらも指定しないようにしています
`failure` が指定されるのは「ファンブル値が6以上となった自動失敗」および「ファンブルした場合に `fumble` と一緒にセットされる」場合で、 `success` がセットされるのは「目標成功度に達した場合」です。
> [Satasupe] Result対応

- test/data/DoubleCross_Korean.toml
- test/data/Dracurouge_Korean.toml
- test/data/LogHorizon_Korean.toml
- test/test_game_system_commands.rb
* 1つのTOMLに複数のgame_systemがある場合、テストを失敗させる。
* このテストで判明した指定ミスを訂正
Memo:
特に多言語対応時の修正漏れが大きいので、今後方針変更があっても多言語ファイルに関してはこのテストがほしいかと思います。
> 1つのTOMLファイルには1つのgame_systemのみを許容

- test/data/StellarKnights.toml
　置き換えルールに（該当するテストケースはあったが、）該当しないテストケースがなかったので、追加。
　（「出目Ｘを出目Ｙに置き換える」という主旨の機能があり、ダイスロール結果にＸが含まれないテストケースがなかった、という意味です）
> [StellarKnights] ダイス目置き換えルールに該当しない出目のテストケースを追加

- lib/bcdice/game_system/BattleTech.rb
- test/data/BattleTech.toml
バトルテックのメック戦士意識維持ロール（`CDx`）を改良しました。
* 2018年発行の「BattleTech: A Game of Armored Combat」p. 44に合わせて、識別子名や処理を改良しました。
* 結果のテキストを分かりやすくしました。
* ダメージ6はロールなしで「死亡」、ダメージ1〜5は2D6の成功判定、とやや複雑な処理だったため、最近のゲームシステムを参考にして結果のテキストを詳しくしました。
* 例1（`CD3`）：`7[5,2]>=7 ＞ 成功` → `CD3 ＞ (2D6>=7) ＞ 7[5,2] ＞ 7 ＞ 成功`
* 例2（`CD6`）：`死亡` → `CD6 ＞ 死亡`
* 結果に成功、失敗、ファンブルを含めました。`CD6` のときはファンブルかつ失敗、`CD1` 〜 `CD5` のときは成功または失敗となります。
> BattleTech: CDxコマンドを改良する

- lib/bcdice/game_system/BattleTech.rb
- test/data/BattleTech.toml
バトルテックの `PPC` コマンドの部位指定取り出しで、該当部分の開始位置を間違えていたのを修正しました（テストケースも、誤りで落ちるように変えました）。また、`getHitResult` の正規表現マッチが甘く、結果的に正しく解釈されてしまうのを修正しました（問題が見つかりにくくなるため）。
> BattleTech: PPCコマンドの構文解析を修正する

- lib/bcdice/game_system/SteamPunkers.rb
- test/data/SteamPunkers.toml
スチームパンカーズの #423 対応です
既存コードにはクリティカルの判断がなかった（成功数の計上で一括処理していた）ため、
ルールブックの記述に基づき出目6の有無をクリティカルの判定としています。
> [SteamPunkers] Result対応

- lib/bcdice/game_system/StellarKnights.rb
- test/data/StellarKnights.toml
　【アタック判定】のダイス数に 0 が指定された場合、メッセージでその旨を表示する。
　今までは結果文字列が `"(0SK) ＞ "` のようになって、不自然かつ不親切だったので。
> [StellarKnights] 【アタック判定】のダイス数に 0 が指定された場合を考慮

- lib/bcdice/game_system/Emoklore.rb
- test/data/Emoklore.toml
#423 の Emoklore: エモクロアTRPG Result 対応になります。
ダブル以上の成功判定をクリティカルとして扱っています。
> [Emoklore] Result対応

- lib/bcdice/game_system/MeikyuKingdomBasic.rb
- test/data/MeikyuKingdomBasic.toml
迷宮キングダム 基本ルールブックにて、過去のPR #218 で欠落した地名決定表(PNTx)、迷宮風景表(MLTx)を再度追記しました
旧版と表が変わっていないので、欠落前同様に派生元クラスに処理を委譲する設計としています。
> [MeikyuKingdomBasic] 過去の変更で漏れた表2つを復元

- lib/bcdice/game_system/TokumeiTenkousei.rb
- test/data/TokumeiTenkousei.toml
#423 TokumeiTenkousei: 特命転攻生のResult対応になります。
※テストケースでいくつか重複しているものがあったので削除しています。
> [TokumeiTenkousei] Result対応

- lib/bcdice/game_system/KemonoNoMori.rb
- test/data/KemonoNoMori.toml
> [KemononoMori] Result対応

- lib/bcdice/common_command/barabara_dice/node.rb
- lib/bcdice/common_command/barabara_dice/result.rb
- lib/bcdice/game_system/NinjaSlayer.rb
- test/data/NinjaSlayer.toml
ニンジャスレイヤーTRPGの `AT`、`EL` コマンドに存在した、`repeat` コマンドで繰り返し実行した場合のバグを修正しました。
これまで `repeat` コマンドで繰り返し実行した場合に、後の方の回で出目が悪い場合でも、意図せず「サツバツ！」等が表示される場合がありました。
https://github.com/bcdice/BCDice/blob/7c0b4e7c4cc617d8b096b1a27c86b5947d8aed5e/lib/bcdice/game_system/NinjaSlayer.rb#L177-L179
上記の部分で、複数回の実行で蓄積された出目を取り、「サツバツ！」等の判定を行っていました。`BarabaraDice::Result#rands` には、複数回の実行結果が蓄積される `Randomizer#rand_results` の値が入ります。#335 で私がこの部分を実装したときに `repeat` を考慮し忘れていたため、 `Randomizer#rand_results` を使ってしまいました。
`BarabaraDice::Result` に、最後に振ったときの出目を記録する以下のメンバを加えました。
* `last_dice_list_list`：出目のグループの配列（例：`[[1, 3], [5, 2]]`）
* `last_dice_list`：すべての出目の配列（例：`[1, 3, 5, 2]`）
NinjaSlayer側では、`BarabaraDice::Result#last_dice_list` を使うように変更しました。関連するテストケースも追加しました。
> NinjaSlayer: repeatコマンド使用時のバグを修正する

- lib/bcdice/game_system/BattleTech.rb
https://github.com/bcdice/BCDice/pull/445#discussion_r625448651 の修正漏れを直しました。繰り返し実行時に出目が蓄積される `Randomizer#rand_results` を使わないようにします。
> BattleTech: Randomizer#rand_results を使わない

- lib/bcdice/game_system/GardenOrder.rb
- lib/bcdice/game_system/ScreamHighSchool.rb
- test/data/AceKillerGene.toml
- test/data/GardenOrder.toml
- test/data/ScreamHighSchool.toml
#423 GardenOrder: ガーデンオーダーのResult対応になります。
ついでに以下の2点に関して修正しています。
- ファンブルとクリティカルが同時に発生した場合はファンブルが優先される (cf. p175)
- 連続攻撃判定で最終的な成功率が50％に満たないものはエラーとして返す (cf. p217)
> [GardenOrder] Result対応およびファンブル境界,連続攻撃の修正

- lib/bcdice/game_system/Cthulhu7th.rb
- test/data/Cthulhu7th.toml
fix #475
新クトゥルフでは目標値100以上についての細則がないが、パルプクトゥルフには細則があるとのこと。
> [Cthulhu7th] 目標値が100以上の場合でも100ファンする

- .rubocop.yml
- lib/bcdice/base.rb
- lib/bcdice/game_system/BattleTech.rb
- lib/bcdice/game_system/DesperateRun.rb
- lib/bcdice/game_system/SkynautsBouken.rb
- lib/bcdice/game_system/StellarKnights.rb
- lib/bcdice/game_system/TrinitySeven.rb
> Endless rangeを使わない

- lib/bcdice/common_command/choice.rb
- test/data/choice.toml
`choise2[A,B,C]` のようにすることで要素の中から指定した数だけ重複なしで複数個選ぶ。
- `choice2[A,B,C]`
- "A", "B", "C" から重複なしで2個選ぶ
- `choice3[A,B,C]`
- "A", "B", "C" から全てが選ばれるが、選ばれる順番によって表示順が変わる。実質的に `["A", "B", "C"].shuffle`
- `choice4[A,B,C]`
- 選択数が要素数を超えているのでエラー
指定したい要素が「AからD」のように連続する項目の場合に「A-D」と省略して記述できる。
パースする際に`choice[A-D]`なら`choice[A,B,C,D]`だと解釈され実行される。
- アルファベット大文字1字の範囲： `A-G` 等
- アルファベット小文字1字の範囲： `a-z` 等
- 数値の範囲： `10-30` 等
以下の両方を満たすときに略記が展開される。
- 省略表記1つのみが指定され、他の要素がないとき
- `choice[A-D, Z]` や `choice[A-D, X-Z]` では展開しない
- `[first]-[last]` が `first <= last` であるとき
`2choice`だと`choice`を2回っぽいので。あと、`choice2`の方が英語の語順に近い。
choiceは対象の要素をかなり自由に書けてしまうので、思ったように書けないというのを避けるために限定的な状況でのみ発動するようにする。
Rubyで複数文字の`Range`や`String#upto`を`to_a`すると挙動が怪しい……
```
irb(main):001:0> ('a'..'bb').to_a
=> ["a", "b", "c", "d", "e", "f", "g", "h", …
```
> choiceの複数選択と連続要素略記

- lib/bcdice/game_system/StellarLife.rb
- test/data/StellarLife.toml
　prefix が誤っていた。
　テストを見ればわかるように、出目と項番がズレているのですが、これは、
- この PR の主旨（特定のコマンドがそもそも実行できない問題の解消）とは異なる
- このコマンドにかぎらず StellarLife のあらゆる表を引くコマンドにわたって発生している問題である
　という観点から、この PR では修正しません。
　（追って別の PR で修正する想定です）
> [StellarLife] 「アバターアルファベット表②」のコマンド（ `AAST` ）が実行できなかったのを修正

- .gitignore
- .rubocop.yml
- Rakefile
- lib/bcdice/common_command.rb
- lib/bcdice/common_command/tally_dice.rb
- lib/bcdice/common_command/tally_dice/node.rb
- lib/bcdice/common_command/tally_dice/parser.y
- test/data/tally_sort.toml
- test/data/tally_ty.toml
- test/data/tally_tz.toml
- test/test_base.rb
- test/test_sai_fic_skill_table.rb
Discordのbcdice-helpサーバで出た質問を基にして、バラバラダイスの出目の個数を数える汎用コマンドを追加してみました。ご意見をいただきながら、使いやすい形にしていきたいと思います。
* きっかけとなったDiscordのbcdice-helpサーバで出た質問では、CoCのシナリオ内の処理で需要があるとのことでした。
* Discordや私の[ツイート](https://twitter.com/ochaochaocha3/status/1447043959205683200)の返信で教えていただいたところ、出目の個数のカウントは複数のシステムにある汎用的なルールと考えられました。具体的には、銀剣のステラナイツ、光砕のリヴァルチャー、魔法学園RPGハーベストにあるとのことです。
* 現在のBCDiceでは、アルケミア・ストラグルが固有コマンド `xUL` で対応しています。ただし、面数が6に固定されており、他の面数で振りたい場合は、手作業で数えるか各システムに固有コマンドを追加する必要がありました。
多くのシステムでバラバラダイスの出目の個数を数えられるようにするため、そのように動作する汎用コマンドを追加します。他の汎用コマンドと同様に、振るダイスの個数と面数を指定できるようにします。
https://github.com/bcdice/BCDice/pull/509#issuecomment-965549815 に合わせた仕様です。
* コマンド名：個数カウントダイス
* クラス名：`BCDice::CommonCommand::TallyDice`
（「tally」は[英語で「集計する」という意味](https://eow.alc.co.jp/search?q=tally)。Rubyではこのコマンドと同様の集計操作が …
> 個数カウントダイスを追加する

- lib/bcdice/game_system/Cthulhu.rb
- test/data/Cthulhu.toml
`RESx-y` が実行できるが、 `RESx` で解釈されていた。
ヘルプには `RES(x-y)` が想定書式なので、 `RESx-y` は実行しないようにする。
> [Cthulhu] RESx-yを実行できないように

- lib/bcdice/game_system/Avandner.rb
- test/data/Avandner.toml
根拠：
- ヘルプメッセージでは、もともと 2 が上限となっている
- ゲームルール上も、閾値が 3 となるケースはない
- 『黒絢のアヴァンドナー』電子版（2020/09/25初版・現行最新）とサプリメント『叡智と栄光』電子版（2020/05/31修正版・現行最新）に対して「クリティカル」で全文検索して、ひととおり記述を確認したつもりです。
> [Avandner] Fix: クリティカル閾値の上限を修正（ 3 → 2 ）

- lib/bcdice/game_system/SwordWorld2_0.rb
- lib/bcdice/game_system/SwordWorld2_5.rb
- lib/bcdice/game_system/sword_world/transcendent_test.rb
超越判定のダイスコマンドおよびアビスカース表について、localeの情報が正しく渡っておらず、Ruby 2.7での単体テスト時にwarnが出る問題を見落しておりましたため、修正しました。
> [SwordWorld2.0][SwordWorld2.5] i18nのロケールが正しく渡っていない箇所を修正

- lib/bcdice/game_system/SwordWorld2_0.rb
- lib/bcdice/game_system/sword_world/rating_options.rb
- lib/bcdice/game_system/sword_world/rating_parsed.rb
- lib/bcdice/game_system/sword_world/rating_parser.y
- test/test_sword_world_rating_command_parser.rb
#516 の対応PRです。
- パースしたオプションの結果をhashではなく専用のクラスに格納し、一部パースエラーに関わる判定をメソッド化
- パース後の正規化処理を、Parsedのインスタンスを作成した直後に一度だけ行うようにする
- その他細かい処理を整理
>  [SwordWorld2.0] [SwordWorld2.5] レーティング表まわりのリファクタリング

- lib/bcdice/common_command/add_dice/node.rb
- lib/bcdice/common_command/add_dice/parser.y
- test/data/None.toml
- test/test_add_dice.rb
- test/test_add_dice_parser.rb
https://github.com/bcdice/BCDice/pull/527#issuecomment-1017562913 より
> 別途 `nMAX` 相当の共通コマンドの提案
> 共通コマンドを作る場合、`xDyKH1` の別書式として `xDyMAX` とするのが良いと思います。
`x` = ダイス数
`y` = ダイス面数
`xDyMAX` （ `xDyKH1` 互換）
`xDMAX` （面数省略）（ `xDKH` 互換）
`xDyMIN` （ `xDyKL1` 互換）
`xDMIN` （面数省略）（ `xDKL` 互換）
add_dice を拡張して実現。
この提案をするにいたった背景においては最大値の抽出だけあれば済むのですが、「 max があるのに min がない」のは、汎用コマンドとして利用者の期待・直感に反すると考え、最小値の抽出も提供しています。
より簡便に利用できるコマンドとしての追加であり、省略し得るものは省略できたほうがその目的に適うので、面数の省略をサポートしています。
（「特定の一種類の面数しか使わない」ゲームシステムは現在のところそれなりに多いはずであり、現実のユースケースにおいて省略の恩恵はあると思っています）
---
追記
`xDy[KD][HL]n` 機能において、面数 y と個数 n を省略できるようにしました。
* 面数 y の省略時は `game_system.sides_implicit_d` 相当
* 個数 n の省略時は `1` 相当
で動作します。
> 最大値抽出・最小値抽出の汎用コマンドを追加

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
**今回の修正**
- Resultを使用するように修正
#423 の対応です。[Critical Win]はクリティカル扱い、[Bestial Failure]をファンブル扱いとしています。
[Messy Critical]は悪い結果が発生するクリティカルですが、これもクリティカル扱いとしています。
- テストケースを追加
上記、[Messy Critical]の発生条件を十分にカバーできていなかったので追加しました。
10,10でクリティカル、Hungerダイスの10が混ざると[Messy Critical]なので、Hungerダイス、通常ダイスにそれぞれ10が出たケースとHungerダイスのみ10,10が出たパターンを追加しています。
> Vampire:The Masquerade5thダイスボットのResult対応

- lib/bcdice/game_system/DarkDaysDrive.rb
- test/data/DarkDaysDrive.toml
・サプリに対応（センターの行動決定、対話ダメージ表）
・ページ数を明記（ルールブックのテキストを参照しやすいように）
・イケメンアクション決定表→イケメンアクション表を連続でふるコマンド`IAX`追加
https://bouken.jp/pd/d3/
> ダークデイズドライブ拡張

- lib/bcdice/randomizer.rb
- test/data/randomizer.toml
- test/test_randomizer.rb
ダイス面数の上限 `BCDice::Randomizer::UPPER_LIMIT_DICE_SIDES` を増加。
* 変更前： 1,000
* 変更後： 10,000
1,000 より大きな面数のダイスロールをあつかうゲームに対応するため。
具体的な一例として、[『オバケ空間探索配信ＲＰＧ「実況ゴーストライヴ」』](https://booth.pm/ja/items/3810620)を想定しています。同ゲームでは 10,000 面のダイスロールが発生します。
Discord 上で @ysakasin さんに実装方針を相談済みです。
> ダイス面数の上限を 10,000 に増加

- lib/bcdice/common_command/add_dice.rb
- lib/bcdice/common_command/add_dice/parser.y
- test/data/AddDice.toml
- test/test_add_dice_parser.rb
- test/test_base.rb
- test/test_sai_fic_skill_table.rb
加算ダイスをダイス数を省略した `D20` のような記法に対応する。`D66`は既存のD66コマンドと競合するため、パースエラーにする。
> 加算ダイスで `D20` 記法に対応

- lib/bcdice/game_system/WorldOfDarkness.rb
- test/data/WorldOfDarkness.toml
**【バグ内容】**
本システム群はd10を使用するダイスプール判定であるが、
- 難易度以上の出目が出た数だけ成功
- 1の目の数だけ成功数を打ち消し
- 成功数が0か、1で打ち消されて0になった時は失敗
- ただし、成功数が0かつ1の目がひとつ以上出た時、大失敗
本来は上記ルールで判定されるはずが、「1の目の数＞成功数」であるとき常に大失敗となっていた。
**【修正内容】**
- ひとつでも成功しているのなら1で成功が全て打ち消されても大失敗にはならず通常の失敗になるように修正
- 上記修正のテストケース追加
> 成功数より1の数が多いときに大失敗になるバグ修正

- lib/bcdice/game_system/GoblinSlayer.rb
- test/data/GoblinSlayer.toml
判定コマンド `GS` に大成功と大失敗の閾値を変更するオプションを追加する。
```
GSx@c#f>=y
```
`@c` で大成功を、 `#f` で大失敗を指定する。未指定の場合にはこれまでと同じでc=12、f=2として扱われる。cとfは順不同で指定可能とした。
`c<=f`となった場合の動作は未定義とするが、現時点では大失敗となる。
Ref. #557
> [GoblinSlayer] 判定に大成功と大失敗の閾値変更オプションを追加

- lib/bcdice/game_system/WorldOfDarkness.rb
- test/data/WorldOfDarkness.toml
**【追加機能の背景】**
World of Darknessのシステムでは、下記に例示するように10の目が出た時の振り足しにおいてシステム毎に1の扱いが違う。
- 日本語版ヴァンパイア：ザ マスカレード → 振り足しの1に明示的な記載なし
- 日本語版ワーウフル：ジ アポカリプス → 振り足しで1が出ても打ち消さない
- 日本語版メイジ：ジ アセンション → 振り足しで1が出た時に打ち消しが発生
にもかかわらず、振り足しが発生するコマンドSTSでは1が出ても打ち消されないパターンしか対応できていなかった。
**【追加機能】**
上記の背景を踏まえ、振り足しで1が出た時に成功数との打ち消しが発生するSTBというコマンドを実装した。
また、既存のコマンドであるSTSのヘルプを変更。振り足しにおいて1での打ち消しが発生しないことを明示した。
> [WorldOfDarkness] 振り足しの1で成功数の打ち消しが発生するコマンドを追加

- .github/workflows/test.yml
- Gemfile
- test/setup.rb
RubyGemsの codecov が非推奨になったため、新しいアップローダーに入れ替える。
Ref. #575
> カバレッジ計測に codecov/codecov-action@v3 を使う

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
**【機能追加の背景】**
　コマンドで難易度が省略された際はCritical Win、Messy Criticalは決定できず、Bestial Failureは１つも成功がない場合にのみ判定できるため、「1つも成功が無い場合のBestial Failure」以外は判定結果として表示していなかった。
　この処理自体は間違いではないが、実運用では何のメッセージも出力されないためCritical WinとMessy Critical、Bestial Failureの発生が判定し辛く、見逃されやすい状態であった。特にMessy Critical、Bestial Failureは判定結果として重要であるため、見落とされやすい表示は不適切である。
**【機能追加の内容】**
上記背景を踏まえ、以下の修正を行った。
- 難易度省略時、Critical Win、Messy CriticalとBestial Failureの可能性があるときにそれを示唆するメッセージを表示
- 今回機能追加に合わせてテストケースの修正と追加
- 今回の修正の対応としてヘルプを修正
- それに伴い、Critical（10,10のペアで成功数増加）とCritical Win(Criticalを含む判定が成功した)の区別がわかりにくかったので、分かり易くヘルプ修正
> [VampireTheMasquerade5th] 難易度省略時に判定結果のヒント出力を追加

- lib/bcdice/game_system/Warhammer4.rb
- test/data/Warhammer4.toml
WHコマンドの成功度判定について、失敗時にSLが0だったときルール上は「-0」表記しなくてはいけないが「+0」表記になっていた不具合の修正。
bundle exec rake test:dicebots target=Warhammer4　実行済み。
> 失敗時のSL0表示を+0から-0に修正

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
**【修正の背景】**
このシステムではHungerダイスは追加ダイスとしてではなく、通常のダイスプールの内数として処理される。つまり、ダイスプール９個の技能等を使う時、Hungerダイス３個だった場合、通常ダイス６個Hungerダイス3個で合計９個のダイスプールになるように調整する。
しかし、今までのヘルプでは追加ダイスとして処理するように読み取れてしまう懸念があった。
**【変更の内容】**
ヘルプに以下の内容を追記/修正を行うことでユーザがコマンド仕様を把握しやすくした。
- Hungerダイスが内数であることを明記。
- Hungerダイスがあった場合、ダイスプールの内数として処理することを例示。
- ダイスプールという記述を通常ダイスとし、Hunterダイスとの対比を明確化。
> [VampireTheMasquerade5th] Hungerダイスの取り扱いをヘルプに追加

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
【追加の背景】
VampireTheMasquerade5thでは、判定での成功差分をダメージの算出や特殊能力の効果などに頻繁に使用する。
成功差分は成功度と難易度があれば簡単に算出できる値であったが、ダイスボットの難易度指定コマンドで処理が可能であるにも関わらずこれまで表示してこなかった。
【追加の内容】
上記の背景を踏まえ、難易度指定コマンドで、成功差分を表示するように修正した。
なお、難易度ぴったりの成功は差分が０であるが、これは明示的に表示することとする。
> [VampireTheMasquerade5th] 難易度指定時に成功差分を表示する機能を追加

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
【修正の背景】
　Hunter:the Reckoning5thダイスボットにて[コマンドの正規表現が完全一致ではない旨指摘](https://github.com/bcdice/BCDice/pull/589#discussion_r1038666221)され、同じ正規表現を使用しているVampire:the Masquerade5thダイスボットに対しても修正を行うこととした。
【修正の内容】
以前の正規表現を、
> m = /\A(\d+)?(HRF)(\d+)(\+(\d+))?/.match(command)
以下のように修正した。
> m = /\A(\d+)?(HRF)(\d+)(\+(\d+))?$/.match(command)
> [VampireTheMasquerade5th] コマンドの正規表現が完全一致ではないバグを修正

- lib/bcdice/game_system/AssaultEngine.rb
- test/data/AssaultEngine.toml
Discordサーバー、bcdice-helpにて、アサルトエンジンのダイスボットで成否判定を伴う加算ダイスが振られないというバグが報告された。
継承元の`check_result`がオーバーライドされていたことが原因とみられる。
`check_result`として使われていたメソッドの名称を`return_result`に変更した。
テストとreplで動作を確認。
> [AssaultEngine]Discordで報告されていたバグの修正

- lib/bcdice/game_system/MonotoneMuseum.rb
- test/data/MonotoneMuseum.toml
目標値が不明の場合にクリティカル・ファンブルの判定ができず、2d6>=?[12,2]のように手動でクリティカル・ファンブル値を設定する場合は動作しませんでした。
- 目標値が不明(0または?)の場合でもクリティカル・ファンブルの判定を行います。
- 目標値が不明の場合は、成功・失敗の判定を行いません。
- 目標値不明の場合でも、クリティカル・ファンブル値を設定して動作するように修正しました。
> [MonotoneMuseum]>=?判定を修正

- lib/bcdice/game_system/CastleInGray.rb
- lib/bcdice/game_system/cthulhu7th/rollable.rb
- lib/bcdice/game_system/sword_world/transcendent_test.rb
`# frozen_string_literal: true` が無かったファイルを修正しました。
frozen_string_literalが無いファイルで文字列リテラルをfreezeすると、Opalへの変換時に専用のクラスにラップされる:
```
[String: '灰色城綺譚']
[String: '■ 色占い (BnWm)\n' +
'n: 黒\n' +
'm: 白\n' +
'n, m は1～12の異なる整数\n' +
'\n' +
'例) B12W7\n' +
'例) B5W12\n' +
'\n' +
'■ 悪意の渦による占い (MALn)\n' +
'n: 悪意の渦\n' +
'n は1～12の整数\n' +
'\n' +
'■ その他\n' +
'・感情表 ET\n' +
'・暗示表(黒) BIT\n' +
'・暗示表(白) WIT\n']
```
これが原因と思われる不具合がユーザーから報告された。
> frozen_string_literal対応

- lib/bcdice/game_system/sword_world/transcendent_test.rb
- test/data/SwordWorld2_0.toml
- test/data/SwordWorld2_0_SimplifiedChinese.toml
- test/data/SwordWorld2_5.toml
- test/data/SwordWorld2_5_SimplifiedChinese.toml
〈アステリアの連刃剣〉の効果などで自動成功しても達成値が必要になる場合があり、そのために達成値自体は算出するように動作を変更する。
自動的成功の条件自体に変更はない。
> [SwordWorld2.0/2.5] 超越判定の際に自動的成功した場合でも、達成値算出のために振り足しを行う

- lib/bcdice/game_system/SajinsenkiAGuS.rb
- test/data/SajinsenkiAGuS.toml
- test/data/SajinsenkiAGuS2E.toml
アーガスのダイスで一般判定に「成功レベル」を表示してほしい旨要望があったので、実装してみました。
使用方法等は変わらず、一般判定の成功時に「成功(+2)」などと成功レベルを併記するようにしました。
rubocop通過済みです。
お手隙の際に、ご確認くださいませ。
> 『砂塵戦機アーガス』のダイスを変更しました

- lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
- test/data/RuneQuestRoleplayingInGlorantha.toml
**【背景】**
RuneQuest:Roleplaying in Glorantha(以下、RQG)の判定では01は常にクリティカル、00は常にファンブル、05以下は常に成功、96以上は常に失敗となる。しかし、500%以上の技能値を持つとき、ダイス目が96-99の時でも失敗ではなくスペシャルになるバグが存在していた。
**【修正】**
96以上は失敗する判定の前にスペシャルの判定があり、これにより上記の現象が発生していた。
このため以下のように判定の優先順位を修正した。
１．クリティカル(01、あるいはクリティカル成功値以下)
２．ファンブル(00、あるいはファンブル値以上)
３．失敗(96以上、5以下の出目を除く技能値を超える値)
４．スペシャル(技能値の1/5以下)
５．成功(05以下、あるいは技能値以下)
この修正に伴い、失敗値周りのコメントを上記の処理に合うよう変更。また、テストケースも２例追加した。
> [RuneQuest:Roleplaying in Glorantha]「失敗」判定の優先順位バグ修正

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
**【背景】**
全てのダイスで成功がない(=6未満)の時、Total Failureというファンブル状態になる。
他の状態でヒント情報を出力しているため、Total Failureもチェックし、ヒント情報を表示したい。
**【対応】**
難易度指定、未指定のコマンドにおいて、全てのダイスに成功が無かった時、Total Failureのヒントを出力するように実装。また、Total Failureはfumbleとして処理するようにし、それに伴い、該当するテストケース、ヘルプも修正を行った。
判定失敗時のHungerダイスの"1"でBestial FailureとTotal Failureが同時発生する可能性があるが、以下の理由により排他として実装する。
1. Messy CriticalがCritical Winを上書きするため。
V5,p206にて、Messy CriticalがCritical Winを上書きすることが記述されており、Total Failureもこれに倣うと考えられる。
Critical Win、Total Failureは汎用判定の結果、Messy CriticalとBestial Failureは種族特有(この場合はヴァンパイア)処理。
以下引用。
> However, the presence of the turns the critical win into a messy critical! Martin has a hard choice to make. 
2. V5 DiceRoller( https://realmofdarkness.app/v5/ ) でも、排他として実装されているため。
> [VampireTheMasquerade5th] Total Failureのヒント情報を追加

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
**【背景】**
https://github.com/bcdice/BCDice/pull/644 に記載した通り、V5の現行ルールではHungerダイスの上限は5ダイスであるにも関わらず、6以上のダイス数を指定できてしまう。
**【対応】**
ルールを把握している限り運用上で大きな問題にはならないが、入力ミスに気付かない等のケースを拾うため、5ダイス以上のHungerダイス指定にエラーメッセージを出すように修正、テストケースの追加を行う。
> Vtm5th hunger limit

- lib/bcdice/game_system/HunterTheReckoning5th.rb
- test/data/HunterTheReckoning5th.toml
【背景】
H5にも https://github.com/bcdice/BCDice/pull/649 と同様の問題が存在する。
【対応】
同様に5ダイス以上のDesperation ダイス指定にエラーメッセージを出すように修正、テストケースの追加を行う。
> [Hunter:the Reckoning 5th] Desperation ダイスのリミット実装

- lib/bcdice/game_system/HunterTheReckoning5th.rb
- test/data/HunterTheReckoning5th.toml
**【背景】**
全てのダイスで成功がない(=6未満)の時、Total Failureというファンブル状態になる。
他の状態でヒント情報を出力しているため、Total Failureもチェックし、ヒント情報を表示したい。
関連( https://github.com/bcdice/BCDice/pull/651 )。
**【対応】**
難易度指定、未指定のコマンドにおいて、全てのダイスに成功が無かった時、Total Failureのヒントを出力するように実装。また、Total Failureはfumbleとして処理するようにし、それに伴い、該当するテストケース、ヘルプも修正を行った。
判定失敗時のDesperationダイスの"1"でDespairとTotal Failureが同時発生する可能性があるが、以下の理由により排他として実装する。
1. V5 DiceRoller( https://realmofdarkness.app/v5/ ) のH5コマンドでも、排他として実装されているため。
> [HunterTheReckoning5th] Total Failureのヒント情報を追加

- lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
**【背景】**
RuneQuest:Roleplaying in Gloranthaが未訳だったこともあり、ダイスボット名を英語で作成していた。
しかし、「ルーンクエストスターターセット　日本語版」が2023/12/08に発売されたことで、ブック１、p1の囲み記事にて、システム名称の日本語名が「ルーンクエスト：ロールプレイング・イン・グローランサ」と判明した。
https://www.dlsite.com/home/work/=/product_id/RJ01110001.html
また、ダイスボット作成時の仕様( https://github.com/bcdice/BCDice/pull/637 )で日本語名にすることとしていたが、英語名を使用してしまっていた。
ルーンクエストスタートセット日本語版発売を受け、上記事情を鑑み、ダイスボット名称を「ルーンクエスト：ロールプレイング・イン・グローランサ」といたしたい。
**【修正】**
ダイスボット名称を日本語名称（「ルーンクエスト：ロールプレイング・イン・グローランサ」）に変更。
> [RuneQuest:Roleplaying in Glorantha] システム名を英語から日本語に変更

- lib/bcdice/game_system/NightWizard.rb
- lib/bcdice/game_system/NightWizard3rd.rb
ナイトウィザード3rdに関して
https://github.com/bcdice/BCDice/pull/252
```
ファンブルのとき、常時発動ではない（能動的な）効果による修正値は適用されない。
「ナイトウィザード The 3rd Edition」ではファンブルでも適用される
```
この記述通り、ルール上、2rdと若干違いがある。
そして、3rdの`HELP_MESSAGE`は2rdを継承しており、同じになっている。
つまり、3rdの処理は正しいのだけど、説明文が間違っている。
なので、3rd側に`HELP_MESSAGE`を追加して、訂正した。
ナイトウィザード2ndに関して
```
aNW+b@x#y$z+c
x : クリティカル値のカンマ区切り（省略時 10）
y : ファンブル値のカンマ区切り（省略時 5）
z : プラーナによる達成値補正のプラーナ消費数（ファンブル時には適用されない）
```
そして、正規表現上`@x#y$z`はカンマ区切りのリストで指定できるように書かれているのだけど、
```ruby
command.critical_numbers = m[3] ? m[3].split(',').map(&:to_i) : [10]
command.fumble_numbers = m[4] ? m[4].split(',').map(&:to_i) : [5]
command.prana = m[5]&.to_i
```
ここで、`command.prana`はリストを取れないので、マッチしないように正規表現を変更した。
> NightWizard3rd: Fix help message

- lib/bcdice/game_system/VampireTheMasquerade5th.rb
- test/data/VampireTheMasquerade5th.toml
**【背景】**
https://github.com/bcdice/BCDice/pull/615 の修正にて、内数でのHungerダイス指定(VMIコマンド)がダイスプールを上回った時にエラーとするようにした。しかし、以下のようにルール上は全てのダイスプールがHungerダイスとして扱われるだけで判定不能になるわけではない。
V5,p205から引用
> When a player builds a dice pool for a vampire character, they exchange regular dice from that pool for Hunger dice on a one-for-one basis.
> If the dice pool for the roll is lower than the character’s Hunger, simply roll a number of Hunger dice equal to the dice pool.
このため、エラーにならないように修正を行う必要がある。
**【対応】**
上記の通り、VMIコマンドにてダイスプールより大きなHungerダイスが指定されてもエラーとせず、ダイスプールと同数のダイスがHungerダイスとして扱われるように修正した。
ただし、ダイスプールが0指定のときにHungerダイスが指定されたときは、従来通りエラーとして処理する。
> [VampireTheMasquerade5th] ダイスプールよりHungerダイスよりが大きい時に全てのダイスがHungerダイスになるよう変更

- lib/bcdice/game_system/WerewolfTheApocalypse5th.rb
- test/data/WerewolfTheApocalypse5th.toml
**【背景】**
https://github.com/bcdice/BCDice/pull/653 の投稿にて、内数でのRagerダイス指定(WAIコマンド)がダイスプールを上回った時にエラーとするようにした。しかし、ルール上は全てのダイスプールがRageダイスとして扱われるだけで判定不能になるわけではない。このため、エラーにならないように修正を行う必要がある。
参考：W5,p133から引用
> Rage Dice
> For each point of Rage possessed by a character, one Rage die replaces one of the regular dice when assembling dice pools.
**【対応】**
上記の通り、WAIコマンドにてダイスプールより大きなRageダイスが指定されてもエラーとせず、ダイスプールと同数のダイスがRageダイスとして扱われるように修正した。
ただし、ダイスプールが0指定のときにRageダイスが指定されたときは、従来通りエラーとして処理する。
> [WerewolfTheApocalypse5th] ダイスプールよりRageダイスよりが大きい時に全てのダイスがRageダイスになるよう変更

- lib/bcdice/game_system/ConvictorDrive.rb
- test/data/ConvictorDrive.toml
discord-helpチャンネルにおいての要望を実装しました。
> 調査フェイズではクリティカルラインと目標値が固定になるため
という利便性の観点での実装となります。
> [ConvictorDrive] 目標値のデフォルト値を5とする

- lib/bcdice/game_system/SwordWorld.rb
- test/data/SwordWorld2_0.toml
- test/data/SwordWorld2_5.toml
ルールにない挙動であるが、これまでの実装は明らかにおかしいので、より妥当性のある挙動とする
> [SwordWorld,SwordWorld2_0,SwordWorld2_5] 首切り刀をマイナスで振った時に、威力100に一周せず0で固定されるように変更

- lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
- test/data/RuneQuestRoleplayingInGlorantha.toml
**【背景】**
当ダイスボットでは、Critical Successと Special Success をこれまでクリティカル、スペシャルとしていたが、ルーンクエスト ロールプレイング イン グローランサ の 日本語版スタートセットでは決定的成功、効果的成功と訳されている。
**【修正】**
上記の訳語に合わせるために Critical Success を決定的成功と Special Success を効果的成功へと変更を行った。
また、この修正に伴い、コメント、ヘルプ、テストケースの文言も修正した。
> [RuneQuest:Roleplaying in Glorantha] 成功段階の文言を日本語版に合わせて変更

- lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
- test/data/RuneQuestRoleplayingInGlorantha.toml
**【背景】**
これまで決定的成功時には「決定的成功/効果的成功」と表示していた。これは、攻撃時に決定的成功に効果的成功両方の効果が入っているとして、それを明示する意図であった。しかし、ルーンクエスト ロールプレイング イン グローランサ の 日本語版スタートセットp32において、決定的成功が効果的成功を含んだ形で記述されており、効果的成功が二重に適用されるような誤解を招きかねない表記であることがわかった。
**【修正】**
上記の問題に対応するため決定的成功時の表示を「決定的成功」のみとして、誤解を引き起こさないようルールブック通りの表記に修正した。
また、この修正に伴い、コメント、テストケースなどの文言も修正した。
> [RuneQuest:Roleplaying in Glorantha] 決定的成功時の表示を変更

- lib/bcdice/game_system/RogueLikeHalf.rb
- test/data/RogueLikeHalf.toml
ローグライクハーフ( https://booth.pm/ja/items/4671946 ) に「宝物表」を実装しました。
■宝物表　NTT+x     x:修正値
普通の表とちがって、修正値が入るのでサタスペを参考にしました。
お手隙の際に、ご確認くださいませ。
> [ローグライクハーフ] 宝物表の実装

- lib/bcdice/game_system/Cthulhu7th.rb
- test/data/Cthulhu7th.toml
- test/data/PulpCthulhu.toml
こんにちは、いつもお世話になっています。
HelpサーバにてD-51様より指摘があった新・クトゥルフ神話TRPGのCCコマンドの表記揺れを修正しました。
https://discord.com/channels/757618761854484591/757624116965670993/1340675183564034069
> [Cthulhu7th]新・クトゥルフ神話TRPGのCCコマンドの表記揺れ修正

- lib/bcdice/game_system/RuneQuestRoleplayingInGlorantha.rb
- test/data/RuneQuestRoleplayingInGlorantha.toml
【背景】
ルーンクエスト：ロールプレイイング イン グローランサ(以下RQG)のコマンドの記法は、同じBRPシステムであるクトゥルフ神話TRPGのものを参考にある程度の互換性を持つように実装した。その結果、RQGでも「CC<=90」と同じような「RQG<=90」というコマンド書式となったが、しかしこれはチャットパレットを自動生成可能なキャラクターシートサイトを持つクトゥルフ神話TRPGに比べて、手でコマンド入力する機会が多いRQGでは手間であった。
【修正】
そこで、手入力の手間を軽減するために新たな略記判定コマンド RQG[判定確率] を追加することとし、ヘルプ、テストケースも略記判定コマンドに対応した。
> [RuneQuest:Roleplaying in Glorantha] 略記判定コマンドを追加

- lib/bcdice/game_system/TorgEternity.rb
- test/data/TorgEternity.toml
TORG Eternity( http://www.shinkigensha.co.jp/book/978-4-7753-1928-4/ )に「コズムポシビリティ」のコマンドを追加しました。
　・CPOS
　　"CPOSm"で、コズムポシビリティ使用による1d20のロールを行います。
　　mはポシビリティを使用する前のロール結果を入れて下さい。
　　出目が10未満の場合でも、10への読み替えが行われません。
　　振り足しは自動で行い、20の出目が出たときには技能無し値も並記します。
通常のポシビリティーとは違い、10未満の時に読み替えが発生しません。
また、ArithmeticEvaluatorをArithmeticに置き換えました。
以上、ご確認ください。
> [TORG Eternity]コズムポシビリティに対応
