- src/diceBot/LogHorizon.rb
- src/diceBot/StellarKnights.rb
> Ruby 2.3.8/2.4.6 での失敗テストを修正

- src/diceBot/DiceBot.rb
> スペル修正: どどんとふで使用しているため元に戻す

- src/TableFileData.rb
> Re-create TableFileData.rb

- src/bcdiceCore.rb
まだありました。Array.lastは読み込みのみっぽいのでこうなってしまいますが……
> String#<<を使わない

- src/bcdice.rb
- src/bcdiceGui.rb
- src/test.rb
- src/test/others/testArgs.rb
- src/test/others/testCard.rb
- src/test/others/testIniFile.rb
- src/test/others/testPointer.rb
- src/test/others/testSecretDice.rb
文字列結合と間違えないように、 `Array.push` を使用しました
> fix $LOAD_PATH

- README.md
- codecov.yml
- src/Gemfile
- src/test/setup.rb
@esnya さんによる提案
Code Climate、Coverallsと比較した上で採用を決定した。
> Codecovでテストカバレッジを可視化する

- src/test/data/None.txt
- src/utils/ArithmeticEvaluator.rb
> Fix unary bug

- src/.rubocop.yml
- src/.rubocop_todo.yml
- src/Rakefile
- src/test/testDiceBotLoaders.rb
- src/test/testDiceBotPrefixesCompatibility.rb
- src/test/testDiceBots.rb
Test Runner は Rake に任せたほうがスッキリしないでしょうか。
> [Proposal] RakefileをSimplify

- src/diceBot/WorldOfDarkness.rb
> WorldOfDarknessの正規表現をシンプル化

- src/bcdiceCore.rb
- src/diceBot/Amadeus.rb
- src/diceBot/Amadeus_Korean.rb
- src/diceBot/BarnaKronika.rb
- src/diceBot/ChaosFlare.rb
- src/diceBot/DetatokoSaga.rb
- src/diceBot/DetatokoSaga_Korean.rb
- src/diceBot/DiceBot.rb
- src/diceBot/DiceBotLoader.rb
- src/diceBot/DoubleCross.rb
- src/diceBot/HatsuneMiku.rb
- src/diceBot/MetalHeadExtream.rb
- src/diceBot/Postman.rb
- src/diceBot/SwordWorld2_0.rb
主にbcdice-jsのパッチから、
> *1/3 が整数にならないのはOpalやbcdice-jsで直すべき
> * divmod が活用できる部分はBCDice側で取り込む
> * それ以外の種々の変更もRubyにメリットがあるので取り込む
に適合しそうなものを抽出しました。
> ちょっとした修正まとめ

- src/diceBot/Illusio.rb
- src/diceBot/Postman.rb
- src/diceBot/Raisondetre.rb
Travis-CI のログを眺めていて見つけました。
テストには通りましたが、どのゲームのルールブックも持っていないため、この修正のために誤った判定になってしまった可能性があります。
もし持っている方(もしくはこれらのゲームをご存じの方)がいらっしゃいましたら、確認を頂けないでしょうか。
* [晃天のイルージオ](http://shop-cokage.net/ilusio.html)
* [壊れた世界のポストマン](http://shop-cokage.net/postman.html)
* [叛逆レゾンデートル](http://shop-cokage.net/raisondetre.html)
※リンク先が[こかげ書店](http://shop-cokage.net)さんの紹介ページになっていますが、特に意図はありません。
> スペルミスを修正 @sortTye -> @sortType

- README.md
[Pull Requestを送る前に確認したいこと](https://github.com/bcdice/BCDice/wiki/Pull-Request%E3%82%92%E9%80%81%E3%82%8B%E5%89%8D%E3%81%AB%E7%A2%BA%E8%AA%8D%E3%81%97%E3%81%9F%E3%81%84%E3%81%93%E3%81%A8) へのリンクが
うまく貼れてないようだったので、その修正です。
> README の wiki へのリンク修正

- CHANGELOG.md
- src/configBcDice.rb
- src/diceBot/DungeonsAndDragons.rb
- src/diceBot/Pathfinder.rb
- src/test/data/DungeonsAndDragons.txt
- src/test/testDiceBotLoaders.rb
`DungeonsAndDoragons` ->  `DungeonsAndDragons`
> ダンジョンズ&ドラゴンズのIDを修正

- src/bcdiceCore.rb
> rand_resultsを初期化しておくようにする

- src/dice/add_dice/node.rb
- src/dice/add_dice/randomizer.rb
数式表現等、他の文字列生成系がノード側にあるので、それに合わせます。分担により、多値返却も不要になりました。
> AddDice: ダイスロール結果の文字列をノード側で作る

- src/bcdiceCore.rb
> BCDice@isMessagePrintedを削除する

- src/diceBot/VampireTheMasquerade5th.rb
- src/test/data/VampireTheMasquerade5th.txt
Vampire:the Masquerade5版のダイスボットを作成しました。
ご確認ください。
> Vampire:the Masquerade5thダイスボット作成

- src/diceBot/ParanoiaRebooted.rb
- src/test/data/ParanoiaRebooted.txt
パラノイア リブーテッド用のダイスボット, およびテストデータを作成いたしました.
ご確認ください.
> Paranoia Rebootedダイスボット追加

- src/diceBot/RecordOfLodossWar.rb
- src/test/data/RecordOfLodossWar.txt
> ロードス島戦記RPGを追加

- src/diceBot/DeadlineHeroes.rb
> デッドラインヒーローズRPGのソートキーを修正

- src/diceBot/VampireTheMasquerade5th.rb
ヘルプに誤記がありましたので、その修正を行いました。
それに伴い、下記の修正もしております。
- ヘルプのコマンド名が一部間違っていたのを修正（VTF→VMF)
- camelCaseをsnake_caseに修正
- ダイスボット名を英語に修正
> Vtm dicebot誤記とダイスボット名修正

- .github/workflows/coverage.yaml
- Gemfile
CodeCovの挙動が怪しいのでCode Climateを使ってみる
> Code Climateを使う

- lib/bcdice/common_command/add_dice.rb
- lib/bcdice/common_command/add_dice/node.rb
- lib/bcdice/common_command/add_dice/parser.rb
- lib/bcdice/common_command/add_dice/randomizer.rb
- test/add_dice_parser_test.rb
> AddDiceのリファクタリングをする

- lib/bcdice/common_command/barabara_dice.rb
- lib/bcdice/game_system/NinjaSlayer.rb
- lib/bcdice/game_system/ShadowRun5.rb
やったこと
- パースをクラスメソッドに分離
- パース後の情報をインスタンス変数に入れる
- 外部からの呼び出しを `BarabaraDice.#eval` にする
- `BarabaraDice#eval` が `Result` を返す
Ref. #280
> BaranbaraDiceをリファクタリング

- lib/bcdice/common_command/calc.rb
> Calc.#eval で処理を完結させる

- lib/bcdice/common_command/choice.rb
> Choiseをリファクタリング

- lib/bcdice/common_command/d66_dice.rb
> D66Diceをリファクタリング

- lib/bcdice/common_command/reroll_dice.rb
> RerollDiceのリファクタリング

- lib/bcdice/common_command/upper_dice.rb
> UpperDiceをリファクタリング

- lib/bcdice/common_command/version.rb
> Versionコマンドをリファクタリング

- Gemfile
- Rakefile
[失敗例](https://github.com/bcdice/BCDice/pull/330/checks?check_run_id=1581470014)
> Rake 13.0.2でテストがうまく動かない問題を修正

- lib/bcdice/user_defined_dice_table.rb
- test/test_user_defined_dice_table.rb
> [UserDefinedDiceTable] 結果をBCDice::Resultで返す

- lib/bcdice/game_system/CodeLayerd.rb
- test/data/CodeLayerd.toml
* デフォルトダイスを10面に
* リファクタリング
* スネークケースに書き換え
* 関数を統合（やや長く見えますが、直線的な処理）
> コード：レイヤードのリファクタリングとデフォルトダイス変更

- lib/bcdice/loader.rb
- `BCDice#.all_game_systems`: `bcdice/game_system` をrequireする
- `BCDice#.dynamic_load`: クラス名指定からID指定に変更
> ローダーの挙動を変更する

- lib/bcdice/game_system/Illusio.rb
codeclimateで`Consider simplifying this complex logical expression`と言われていたのが気になったので。
正規表現絡みの整理と、スネークケース化が中心です
https://codeclimate.com/github/bcdice/BCDice/issues?severity%5B%5D=critical&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed
> 晃天のイルージオをリファクタリング

- lib/bcdice/game_system/OrgaRain.rb
codeclimateでConsider simplifying this complex logical expressionと言われていたのが気になったので。
正規表現絡みの整理と、スネークケース化が中心です
https://codeclimate.com/github/bcdice/BCDice/issues?severity%5B%5D=critical&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed
> オルガレインをリファクタリング

- lib/bcdice/game_system/sword_world/rating_parser.y
https://yard.bcdice.org/BCDice.html の Overview に SwordWorld::RatingParser のコメントが出現しているため、その修正
> YARDコメントの修正

- lib/bcdice/game_system/AceKillerGene.rb
- lib/bcdice/game_system/Chill.rb
- lib/bcdice/game_system/GardenOrder.rb
- lib/bcdice/game_system/ScreamHighSchool.rb
- test/test_game_system_commands.rb
#412 の要望の第一歩として、テストケースに書かれているコマンドは全て `command_pattern` に一致するようにしたいです。
> command_patternのテスト

- lib/bcdice/game_system/CodeLayerd.rb
- test/data/CodeLayerd.toml
* Result対応
* 目標値0(>=0)とできない軽微なバグ修正
* リファクタリング
> [コード:レイヤード]Resultに対応

- lib/bcdice/game_system/LogHorizon.rb
- test/data/LogHorizon.toml
- test/data/LogHorizon_Korean.toml
#423 LogHorizon, LogHorizon:Korean の対応
> [ログ・ホライズン] Resultを使用

- lib/bcdice/game_system/DeadlineHeroes.rb
- test/data/DeadlineHeroes.toml
> [DeadlineHeroes] Result対応

- lib/bcdice/game_system/FutariSousa.rb
- test/data/FutariSousa.toml
- test/data/FutariSousa_Korean.toml
#423 フタリソウサの対応
FutariSousa, FutariSousa:Korean
ファンブルのテストケースが無かったので追加しました
> [FutariSousa] Result対応

- lib/bcdice/game_system/Skynauts.rb
- test/data/Skynauts.toml
> [Skynauts] 歯車の塔の探空士（六畳間幻想空間）Result対応

- lib/bcdice/game_system/Satasupe.rb
サタスペの性業値コマンドをsuffix_numberを用いて記述し直しました。
> [Satasupe] 性業値コマンドをsuffix_numberを用いて記述

- lib/bcdice/game_system/BlindMythos.rb
- test/data/BlindMythos.toml
#423 の BlindMythos: 禁書封印譚 ブラインド・ミトスRPGのResult対応になります。
- ファンブル：汚染が発生した
- クリティカル：禁書ビットを獲得した
という扱いにしています。
> [BlindMythos] Result対応

- lib/bcdice/game_system/Yggdrasill.rb
- test/data/Yggdrasill.toml
> [Yggdrasill] repeatコマンド利用時のバグを修正

- lib/bcdice/game_system/AngelGear.rb
- test/data/AngelGear.toml
> [AngelGear]Result対応

- lib/bcdice/game_system/TorgEternity.rb
> 「トーグ エタニティ」に変更

- lib/bcdice/game_system/Dracurouge.rb
- test/data/Dracurouge.toml
- test/data/Dracurouge_Korean.toml
> [Dracurouge] 抗い判定で合計値を表示する

- lib/bcdice/game_system/StellarLife.rb
> [StellarLife] Fix typo in class name

- lib/bcdice/game_system/StrangerOfSwordCity.rb
- test/data/StrangerOfSwordCity.toml
> [剣の街の異邦人]Issue 423 Result対応

- lib/bcdice/game_system/Elysion.rb
- test/data/Elysion.toml
> [エリュシオン]Issue 423 Result対応

- lib/bcdice/common_command/d66_dice.rb
- test/data/D66Dice.toml
- test/data/None.toml
#567 に対応。
テストファイルとして`D66Dice.toml`を追加。
> D66ダイスの並べ替え指定を小文字に対応

- i18n/Emoklore/ja_jp.yml
- lib/bcdice/game_system/Emoklore.rb
- test/data/Emoklore.toml
> [Emoklore] i18n対応と出力文言の変更

- i18n/Arianrhod/ja_jp.yml
- lib/bcdice/game_system/Arianrhod.rb
> [Arianrhod] i18n対応

- lib/bcdice/game_system/CyberpunkRed.rb
- test/data/CyberpunkRed.toml
> [CyberpunkRed] 判定コマンドの比較記号の誤りを修正

- i18n/SwordWorld/ja_jp.yml
- lib/bcdice/game_system/SwordWorld.rb
> [SwordWorld] i18nの漏れ

- lib/bcdice/game_system/Bloodorium.rb
- test/data/Bloodorium.toml
> [Bloodorium] DCで2桁以上のダイスを指定できない問題を修正

- lib/bcdice/game_system/CyberpunkRed.rb
> [CyberpunkRed] 判定のヘルプメッセージを修正

- lib/bcdice/game_system/ShinobiGami.rb
> [ShinobiGami] ヘルプメッセージの誤植修正と不足分の追記

- lib/bcdice/game_system/MamonoScramble.rb
> [MamonoScramble]割り算を切り上げに変更

- lib/bcdice/game_system/KyokoShinshoku.rb
- test/data/KyokoShinshoku.toml
ダイスサイズへの計算式の許容、ダイス個数0個以下のときの特殊処理を追加しました。
ご確認の程、よろしくお願いいたします。
lib/bcdice/game_system/KyokoShinshoku.rb
test/data/KyokoShinshoku.toml
> 虚構侵蝕TRPGの有利不利とダイス数0以下の特殊処理に対応

- lib/bcdice/dice_table/range_table.rb
- test/test_range_table.rb
サイバーパンクREDのi18n化（#705）において必要であるための実装
> RangeTableにfrom_i18nを実装

- lib/bcdice/game_system.rb
- lib/bcdice/game_system/Agnostos.rb
- test/data/Agnostos.toml
公式サイト：https://agnostos-official.jimdofree.com/
> 「アグノストス」を追加

- i18n/DungeonsAndDragons5/ja_jp.yml
- lib/bcdice/game_system/DungeonsAndDragons5.rb
Dungeons&Dragons第5版用ソースの日本語出力部分をi18n化
> Dungeons&Dragons第5版用ソースの日本語出力部分をi18n化
